name: Install dependencies

runs:
  using: composite
  steps:
    - name: Install apt dependencies and upgrade pip
      shell: bash -el {0}
      run: |
        apt-get update && apt-get install -y libxrender1
